/* The following code was generated by JFlex 1.4.1 on 1/4/12 9:32 PM */

/** Based on the arc lexer (http://code.google.com/p/intelli-arc/) **/

package com.r4intellij.lang.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.r4intellij.psi.RTypes;

import static com.r4intellij.psi.RTypes.*;


/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 1/4/12 9:32 PM from the specification file
 * <tt>src/com/r4intellij/lang/lexer/r.flex</tt>
 */
public class _RLexer implements FlexLexer {

    /**
     * initial size of the lookahead buffer
     */
    private static final int ZZ_BUFFERSIZE = 16384;

    /**
     * lexical states
     */
    public static final int YYINITIAL = 0;

    /**
     * Translates characters to character classes
     */
    private static final String ZZ_CMAP_PACKED =
            "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\53\1\15" +
                    "\1\4\1\67\1\64\1\57\1\0\1\45\1\46\1\63\1\13\1\44" +
                    "\1\61\1\6\1\65\1\7\11\10\1\43\1\42\1\56\1\54\1\55" +
                    "\1\71\1\70\4\5\1\12\6\5\1\11\1\5\1\40\6\5\1\41" +
                    "\5\5\1\51\1\14\1\52\1\66\1\5\1\0\1\34\1\33\1\21" +
                    "\1\5\1\31\1\16\1\5\1\27\1\23\1\5\1\35\1\30\1\5" +
                    "\1\20\1\24\1\37\1\5\1\25\1\32\1\22\1\17\1\5\1\26" +
                    "\1\36\2\5\1\47\1\60\1\50\1\62\uff81\0";

    /**
     * Translates characters to character classes
     */
    private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 =
            "\1\0\2\1\1\2\1\3\1\0\2\4\1\5\1\6" +
                    "\10\3\1\7\1\10\1\11\1\12\1\13\1\14\1\15" +
                    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25" +
                    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35" +
                    "\1\36\1\0\1\4\1\0\1\4\2\6\3\3\1\37" +
                    "\5\3\1\40\1\41\1\42\1\43\1\44\1\45\1\46" +
                    "\1\47\1\50\1\51\2\0\1\31\1\52\1\4\1\0" +
                    "\1\3\1\53\6\3\1\54\1\0\1\55\1\3\1\56" +
                    "\2\3\1\57\1\3\1\60\1\61\2\3\1\62\1\63" +
                    "\1\3\1\64\1\3\1\65";

    private static int[] zzUnpackAction() {
        int[] result = new int[100];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 =
            "\0\0\0\72\0\164\0\256\0\350\0\u0122\0\u015c\0\u0196" +
                    "\0\164\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2\0\u032c" +
                    "\0\u0366\0\u03a0\0\164\0\u03da\0\164\0\164\0\164\0\164" +
                    "\0\164\0\u0414\0\u044e\0\u0488\0\u04c2\0\u04fc\0\u0536\0\u0570" +
                    "\0\u05aa\0\u05e4\0\164\0\164\0\u061e\0\164\0\164\0\164" +
                    "\0\164\0\164\0\u0658\0\u0692\0\u06cc\0\164\0\u0706\0\164" +
                    "\0\u0740\0\u077a\0\u07b4\0\350\0\u07ee\0\u0828\0\u0862\0\u089c" +
                    "\0\u08d6\0\u0910\0\164\0\164\0\164\0\164\0\164\0\164" +
                    "\0\164\0\164\0\164\0\u094a\0\u0984\0\164\0\164\0\u09be" +
                    "\0\u09be\0\u09f8\0\350\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a" +
                    "\0\u0b54\0\164\0\u0b8e\0\164\0\u0bc8\0\350\0\u0c02\0\u0c3c" +
                    "\0\350\0\u0c76\0\350\0\164\0\u0cb0\0\u0cea\0\350\0\350" +
                    "\0\u0d24\0\350\0\u0d5e\0\350";

    private static int[] zzUnpackRowMap() {
        int[] result = new int[100];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;  /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpackTrans();

    private static final String ZZ_TRANS_PACKED_0 =
            "\1\0\1\2\2\3\1\4\1\5\1\6\1\7\1\10" +
                    "\2\5\1\11\1\0\1\12\1\13\1\5\1\14\2\5" +
                    "\1\15\1\5\1\16\1\17\2\5\1\20\1\5\1\21" +
                    "\4\5\1\22\1\5\1\23\1\24\1\25\1\26\1\27" +
                    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37" +
                    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47" +
                    "\1\50\1\51\1\52\2\0\1\3\161\0\1\4\2\0" +
                    "\67\4\5\0\6\5\3\0\24\5\36\0\1\53\2\54" +
                    "\67\0\1\54\2\7\1\0\1\55\16\0\1\55\46\0" +
                    "\1\54\2\10\1\56\1\55\16\0\1\55\40\0\14\12" +
                    "\1\57\1\60\54\12\5\0\6\5\3\0\1\5\1\61" +
                    "\4\5\1\62\15\5\35\0\6\5\3\0\13\5\1\63" +
                    "\10\5\35\0\6\5\3\0\1\64\23\5\35\0\6\5" +
                    "\3\0\13\5\1\65\10\5\35\0\6\5\3\0\11\5" +
                    "\1\66\12\5\35\0\6\5\3\0\12\5\1\67\11\5" +
                    "\35\0\6\5\3\0\7\5\1\70\14\5\35\0\6\5" +
                    "\3\0\23\5\1\71\73\0\1\72\77\0\1\73\72\0" +
                    "\1\73\73\0\1\74\71\0\1\75\71\0\1\76\71\0" +
                    "\1\77\4\0\1\100\67\0\1\101\72\0\1\102\66\0" +
                    "\1\103\37\0\1\104\1\105\11\0\1\105\24\0\1\105" +
                    "\1\106\1\105\12\0\1\107\72\0\2\54\1\0\1\55" +
                    "\16\0\1\55\47\0\2\110\2\0\1\111\45\0\1\111" +
                    "\10\0\1\12\2\0\67\12\5\0\6\5\3\0\2\5" +
                    "\1\112\21\5\35\0\6\5\3\0\7\5\1\113\14\5" +
                    "\35\0\6\5\3\0\20\5\1\114\3\5\35\0\6\5" +
                    "\3\0\21\5\1\115\2\5\35\0\6\5\3\0\5\5" +
                    "\1\116\16\5\35\0\6\5\3\0\14\5\1\117\7\5" +
                    "\35\0\6\5\3\0\13\5\1\120\10\5\35\0\4\5" +
                    "\1\121\1\5\3\0\24\5\73\0\1\122\46\0\1\123" +
                    "\135\0\1\124\14\0\2\110\66\0\6\5\3\0\3\5" +
                    "\1\125\20\5\35\0\6\5\3\0\4\5\1\126\17\5" +
                    "\35\0\6\5\3\0\13\5\1\127\10\5\35\0\6\5" +
                    "\3\0\12\5\1\130\11\5\35\0\6\5\3\0\13\5" +
                    "\1\131\10\5\35\0\6\5\3\0\16\5\1\132\5\5" +
                    "\35\0\4\5\1\133\1\5\3\0\24\5\114\0\1\134" +
                    "\12\0\6\5\3\0\4\5\1\135\17\5\35\0\6\5" +
                    "\3\0\16\5\1\136\5\5\35\0\6\5\3\0\13\5" +
                    "\1\137\10\5\35\0\6\5\3\0\17\5\1\140\4\5" +
                    "\35\0\6\5\3\0\5\5\1\141\16\5\35\0\6\5" +
                    "\3\0\4\5\1\142\17\5\35\0\6\5\3\0\6\5" +
                    "\1\143\15\5\35\0\6\5\3\0\2\5\1\144\21\5" +
                    "\30\0";

    private static int[] zzUnpackTrans() {
        int[] result = new int[3480];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;
    private static final char[] EMPTY_BUFFER = new char[0];
    private static final int YYEOF = -1;
    private static java.io.Reader zzReader = null; // Fake

    /* error messages for the codes above */
    private static final String ZZ_ERROR_MSG[] = {
            "Unkown internal scanner error",
            "Error: could not match input",
            "Error: pushback value was too large"
    };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 =
            "\1\0\1\1\1\11\2\1\1\0\2\1\1\11\11\1" +
                    "\1\11\1\1\5\11\11\1\2\11\1\1\5\11\1\0" +
                    "\1\1\1\0\1\11\1\1\1\11\12\1\11\11\2\0" +
                    "\2\11\1\1\1\0\10\1\1\11\1\0\1\11\7\1" +
                    "\1\11\10\1";

    private static int[] zzUnpackAttribute() {
        int[] result = new int[100];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * the current state of the DFA
     */
    private int zzState;

    /**
     * the current lexical state
     */
    private int zzLexicalState = YYINITIAL;

    /**
     * this buffer contains the current text to be matched and is
     * the source of the yytext() string
     */
    private CharSequence zzBuffer = "";

    /**
     * this buffer may contains the current text array to be matched when it is cheap to acquire it
     */
    private char[] zzBufferArray;

    /**
     * the textposition at the last accepting state
     */
    private int zzMarkedPos;

    /**
     * the textposition at the last state to be included in yytext
     */
    private int zzPushbackPos;

    /**
     * the current text position in the buffer
     */
    private int zzCurrentPos;

    /**
     * startRead marks the beginning of the yytext() string in the buffer
     */
    private int zzStartRead;

    /**
     * endRead marks the last character in the buffer, that has been read
     * from input
     */
    private int zzEndRead;

    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private boolean zzAtBOL = true;

    /**
     * zzAtEOF == true <=> the scanner is at the EOF
     */
    private boolean zzAtEOF;

    /* user code: */
    StringBuffer string = new StringBuffer();

    //helper
    long yychar = 0;


    public _RLexer(java.io.Reader in) {
        this.zzReader = in;
    }

    /**
     * Creates a new scanner.
     * There is also java.io.Reader version of this constructor.
     *
     * @param in the java.io.Inputstream to read input from.
     */
    public _RLexer(java.io.InputStream in) {
        this(new java.io.InputStreamReader(in));
    }

    /**
     * Unpacks the compressed character translation table.
     *
     * @param packed the packed character translation table
     * @return the unpacked character translation table
     */
    private static char[] zzUnpackCMap(String packed) {
        char[] map = new char[0x10000];
        int i = 0;  /* index in packed string  */
        int j = 0;  /* index in unpacked array */
        while (i < 154) {
            int count = packed.charAt(i++);
            char value = packed.charAt(i++);
            do map[j++] = value; while (--count > 0);
        }
        return map;
    }

    public final int getTokenStart() {
        return zzStartRead;
    }

    public final int getTokenEnd() {
        return getTokenStart() + yylength();
    }

    public void reset(CharSequence buffer, int start, int end, int initialState) {
        zzBuffer = buffer;
        zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
        zzCurrentPos = zzMarkedPos = zzStartRead = start;
        zzPushbackPos = 0;
        zzAtEOF = false;
        zzAtBOL = true;
        zzEndRead = end;
        yybegin(initialState);
    }

    // For Demetra compatibility
    public void reset(CharSequence buffer, int initialState) {
        zzBuffer = buffer;
        zzBufferArray = null;
        zzCurrentPos = zzMarkedPos = zzStartRead = 0;
        zzPushbackPos = 0;
        zzAtEOF = false;
        zzAtBOL = true;
        zzEndRead = buffer.length();
        yybegin(initialState);
    }

    /**
     * Refills the input buffer.
     *
     * @return <code>false</code>, iff there was new input.
     * @throws java.io.IOException if any I/O-Error occurs
     */
    private boolean zzRefill() throws java.io.IOException {
        return true;
    }


    /**
     * Returns the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }


    /**
     * Enters a new lexical state
     *
     * @param newState the new lexical state
     */
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }


    /**
     * Returns the text matched by the current regular expression.
     */
    public final CharSequence yytext() {
        return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
    }


    /**
     * Returns the character at position <tt>pos</tt> from the
     * matched text.
     * <p/>
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos the position of the character to fetch.
     *            A value from 0 to yylength()-1.
     * @return the character at position pos
     */
    public final char yycharat(int pos) {
        return zzBufferArray != null ? zzBufferArray[zzStartRead + pos] : zzBuffer.charAt(zzStartRead + pos);
    }


    /**
     * Returns the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }


    /**
     * Reports an error that occured while scanning.
     * <p/>
     * In a wellformed scanner (no or only correct usage of
     * yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen".
     * If this method is called, something is seriously wrong
     * (e.g. a JFlex bug producing a faulty scanner etc.).
     * <p/>
     * Usual syntax/scanner level error handling should be done
     * in error fallback rules.
     *
     * @param errorCode the code of the errormessage to display
     */
    private void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }


    /**
     * Pushes the specified amount of characters back into the input stream.
     * <p/>
     * They will be read again by then next call of the scanning method
     *
     * @param number the number of characters to be read again.
     *               This number must not be greater than yylength()!
     */
    public void yypushback(int number) {
        if (number > yylength())
            zzScanError(ZZ_PUSHBACK_2BIG);

        zzMarkedPos -= number;
    }


    /**
     * Resumes scanning until the next regular expression is matched,
     * the end of input is encountered or an I/O-Error occurs.
     *
     * @return the next token
     * @throws java.io.IOException if any I/O-Error occurs
     */
    public IElementType advance() throws java.io.IOException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        CharSequence zzBufferL = zzBuffer;
        char[] zzBufferArrayL = zzBufferArray;
        char[] zzCMapL = ZZ_CMAP;

        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            yychar += zzMarkedPosL - zzStartRead;

            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = zzLexicalState;


            zzForAction:
            {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL)
                        zzInput = zzBufferL.charAt(zzCurrentPosL++);
                    else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = zzBufferL.charAt(zzCurrentPosL++);
                        }
                    }
                    int zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput]];
                    if (zzNext == -1) break zzForAction;
                    zzState = zzNext;

                    int zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) break zzForAction;
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                case 42: {
                    return R_SYMBOL_FORMALS;
                }
                case 54:
                    break;
                case 38: {
                    return R_LEFT_ASSIGN;
                }
                case 55:
                    break;
                case 43: {
                    return R_FOR;
                }
                case 56:
                    break;
                case 48: {
                    return R_NULL_CONST;
                }
                case 57:
                    break;
                case 52: {
                    return R_REPEAT;
                }
                case 58:
                    break;
                case 6: {
                    yybegin(YYINITIAL);
                    return RTypes.R_STR_CONST;
                }
                case 59:
                    break;
                case 25: {
                    return R_ARITH_MOD;
                }
                case 60:
                    break;
                case 22: {
                    return R_ARITH_MINUS;
                }
                case 61:
                    break;
                case 29: {
                    return R_SLOT;
                }
                case 62:
                    break;
                case 12: {
                    yybegin(YYINITIAL);
                    return RTypes.R_LEFT_BRACE;
                }
                case 63:
                    break;
                case 17: {
                    return R_EQ_ASSIGN;
                }
                case 64:
                    break;
                case 49: {
                    return R_IN;
                }
                case 65:
                    break;
                case 21: {
                    return R_OR;
                }
                case 66:
                    break;
                case 39: {
                    return R_AND2;
                }
                case 67:
                    break;
                case 26: {
                    return R_ARITH_DIV;
                }
                case 68:
                    break;
                case 23: {
                    return R_TILDE;
                }
                case 69:
                    break;
                case 36: {
                    return R_GE;
                }
                case 70:
                    break;
                case 15: {
                    yybegin(YYINITIAL);
                    return RTypes.R_RIGHT_BRACKET;
                }
                case 71:
                    break;
                case 47: {
                    return R_ELSE;
                }
                case 72:
                    break;
                case 44: {
                    yybegin(YYINITIAL);
                    return RTypes.R_NS_GET_INT;
                }
                case 73:
                    break;
                case 41: {
                    return R_RIGHT_ASSIGN;
                }
                case 74:
                    break;
                case 9: {
                    yybegin(YYINITIAL);
                    return R_COMMA;
                }
                case 75:
                    break;
                case 18: {
                    return R_GT;
                }
                case 76:
                    break;
                case 5: {
                    return R_ARITH_PLUS;
                }
                case 77:
                    break;
                case 11: {
                    yybegin(YYINITIAL);
                    return RTypes.R_RIGHT_PAREN;
                }
                case 78:
                    break;
                case 14: {
                    yybegin(YYINITIAL);
                    return RTypes.R_LEFT_BRACKET;
                }
                case 79:
                    break;
                case 8: {
                    yybegin(YYINITIAL);
                    return R_COLON;
                }
                case 80:
                    break;
                case 30: {
                    return R_QUESTION;
                }
                case 81:
                    break;
                case 34: {
                    return R_NE;
                }
                case 82:
                    break;
                case 45: {
                    return R_ARITH_MISC;
                }
                case 83:
                    break;
                case 33: {
                    yybegin(YYINITIAL);
                    return RTypes.R_LBB;
                }
                case 84:
                    break;
                case 46: {
                    return R_NEXT;
                }
                case 85:
                    break;
                case 28: {
                    return R_LIST_SUBSET;
                }
                case 86:
                    break;
                case 1: {
                    yybegin(YYINITIAL);
                    return com.intellij.psi.TokenType.WHITE_SPACE;
                }
                case 87:
                    break;
                case 53: {
                    return R_FUNCTION;
                }
                case 88:
                    break;
                case 35: {
                    return R_EQ;
                }
                case 89:
                    break;
                case 20: {
                    return R_AND;
                }
                case 90:
                    break;
                case 16: {
                    return R_NEGATION;
                }
                case 91:
                    break;
                case 24: {
                    return R_ARITH_MULT;
                }
                case 92:
                    break;
                case 2: {
                    yybegin(YYINITIAL);
                    return R_COMMENT;
                }
                case 93:
                    break;
                case 37: {
                    return R_LE;
                }
                case 94:
                    break;
                case 31: {
                    return R_IF;
                }
                case 95:
                    break;
                case 13: {
                    yybegin(YYINITIAL);
                    return RTypes.R_RIGHT_BRACE;
                }
                case 96:
                    break;
                case 40: {
                    return R_OR2;
                }
                case 97:
                    break;
                case 7: {
                    yybegin(YYINITIAL);
                    return RTypes.R_SEMICOLON;
                }
                case 98:
                    break;
                case 10: {
                    yybegin(YYINITIAL);
                    return RTypes.R_LEFT_PAREN;
                }
                case 99:
                    break;
                case 3: {
                    System.out.print("word:" + yytext());
                    yybegin(YYINITIAL);
                    return RTypes.R_SYMBOL;
                }
                case 100:
                    break;
                case 19: {
                    return R_LT;
                }
                case 101:
                    break;
                case 50: {
                    return R_WHILE;
                }
                case 102:
                    break;
                case 27: {
                    return R_ARITH_EXPONENTIAION;
                }
                case 103:
                    break;
                case 4: {
                    return R_NUM_CONST;
                }
                case 104:
                    break;
                case 51: {
                    return R_BREAK;
                }
                case 105:
                    break;
                case 32: {
                    yybegin(YYINITIAL);
                    return RTypes.R_NS_GET;
                }
                case 106:
                    break;
                default:
                    if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                        zzAtEOF = true;
                        return null;
                    } else {
                        zzScanError(ZZ_NO_MATCH);
                    }
            }
        }
    }


}
